#!/bin/sh

blkid
echo -n 'ROOT: /dev/'
read ROOT
echo -n 'BOOT: /dev/'
read BOOT
echo -n 'SWAP: /dev/'
read SWAP
echo 'Installing...'
DEST=/mnt/dest
mkdir "$DEST" || exit 1
mount "/dev/$ROOT" /mnt/dest || exit 1
mkdir "$DEST/boot" || exit 1
mount "/dev/$BOOT" "$DEST/boot"
unsquashfs /mnt/cdrom/image.squashfs || exit 1
post_unpack squashfs-root || exit 1
cp -a squashfs-root/* "$DEST" || exit 1
rmdir squashfs-root || exit 1
cat > "$DEST/etc/fstab" << EOF
# /etc/fstab: static file system information.
#
# noatime turns off atimes for increased performance (atimes normally aren't 
# needed); notail increases performance of ReiserFS (at the expense of storage 
# efficiency).  It's safe to drop the noatime options if you want and to 
# switch between notail / tail freely.
#
# The root filesystem should have a pass number of either 0 or 1.
# All other filesystems should have a pass number of 0 or greater than 1.
#
# See the manpage fstab(5) for more information.
#

# <fs>			<mountpoint>	<type>		<opts>		<dump/pass>

# NOTE: If your BOOT partition is ReiserFS, add the notail option to opts.
/dev/$BOOT		/boot		ext2		noauto,noatime	1 2
/dev/$ROOT		/		ext3		noatime		0 1
/dev/$SWAP		none		swap		sw		0 0
/dev/cdrom		/mnt/cdrom	auto		noauto,ro	0 0
/dev/fd0		/mnt/floppy	auto		noauto		0 0

EOF
cat > "$DEST/etc/portage/repos.conf" << EOF
[DEFAULT]
main-repo = gentoo

[gentoo]
location = /usr/portage
sync-type = git
sync-uri = git://github.com/matijaskala/ports-2013.git
auto-sync = yes

EOF
mount -B /proc "$DEST/proc"
mount -B /etc/resolv.conf "$DEST/etc/resolv.conf"
chroot "$DEST" git clone git://github.com/matijaskala/ports-2013.git /usr/portage
chroot "$DEST" sh -c "ACCEPT_KEYWORDS='~amd64' emerge -q shadow"
echo "Enter root password"
chroot "$DEST" passwd
umount "$DEST/etc/resolv.conf"
umount "$DEST/proc"
